# Generated by Django 2.0 on 2020-07-08 05:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to='doctor_images')),
                ('designation', models.CharField(blank=True, choices=[('laboratory-director', 'Laboratory Director'), ('pathology-assistant', 'Pathology Assistant')], max_length=255, null=True)),
                ('degree', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Bsc'), (2, 'Diploma')], max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=25, null=True)),
                ('religion', models.CharField(blank=True, choices=[('islam', 'Islam'), ('Hindu', 'Hindu'), ('buddhist', 'Buddhist'), ('cristian ', 'Cristian')], max_length=255, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
    ]
