# Generated by Django 2.0 on 2020-07-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
