# Generated by Django 2.0 on 2020-07-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_staff_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(blank=True, choices=[('Laboratory Director', 'Laboratory Director'), ('Pathology Assistant', 'Pathology Assistant')], max_length=255, null=True),
        ),
    ]
