# Generated by Django 2.1 on 2020-11-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20201122_1114'),
        ('account', '0005_userprofile_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
