# Generated by Django 3.0 on 2020-12-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
    ]
