# Generated by Django 3.0 on 2020-12-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_loggedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
