# Generated by Django 3.0 on 2020-12-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_connectionhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectionHistory',
        ),
    ]
