# Generated by Django 3.0 on 2020-12-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='type',
            new_name='on_type',
        ),
    ]
