# Generated by Django 3.0 on 2020-12-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_auto_20201212_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('return_request', 'Return Request'), ('return_in_transit', 'Return In Transit'), ('returned', 'Returned'), ('refund_initiated', 'Refund Initiated'), ('refunded', 'Refunded')], default='pending_payment', max_length=100),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
