# Generated by Django 3.0 on 2020-12-10 11:27

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='')),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 17, 27, 13, 324963))),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('view', models.IntegerField(blank=True, default=0)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('medicine_image', models.ImageField(blank=True, null=True, upload_to='medcine_images')),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('price', models.FloatField(blank=True, default=1.0)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.MedicineCompany')),
                ('medicine_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.CategoryMedicine')),
            ],
        ),
        migrations.CreateModel(
            name='FoodBlogView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=40)),
                ('session', models.CharField(blank=True, max_length=40)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 12, 10, 17, 27, 13, 324963))),
                ('foodblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodblog', to='home.FoodBlog')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_image', models.ImageField(blank=True, null=True, upload_to='doctor_images')),
                ('designation', models.CharField(blank=True, choices=[('medical-officer', 'Medical Officer'), ('assistant-professor', 'Assistant Professor'), ('associate-professor', 'Associate Professor'), ('Professor ', 'Professor')], max_length=255, null=True)),
                ('degree', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'MBBS'), (2, 'MBBCh'), (3, 'PhD'), (4, 'MPhil'), (5, 'FRCS'), (6, 'DTCD'), (7, 'FCCP'), (8, 'D-Card')], max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=25, null=True)),
                ('religion', models.CharField(blank=True, choices=[('islam', 'Islam'), ('Hindu', 'Hindu'), ('buddhist', 'Buddhist'), ('cristian ', 'Cristian')], max_length=255, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('doctor_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('urgent_resolve', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Doctor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
