# Generated by Django 3.0 on 2020-12-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodblogview',
            name='foodblog',
        ),
        migrations.DeleteModel(
            name='FoodBlog',
        ),
        migrations.DeleteModel(
            name='FoodBlogView',
        ),
    ]
