# Generated by Django 2.0 on 2020-07-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images'),
        ),
    ]
