# Generated by Django 3.0 on 2020-12-10 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_foodblog_foodblogview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 21, 36, 19, 600799)),
        ),
        migrations.AlterField(
            model_name='foodblogview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 21, 36, 19, 601828)),
        ),
    ]
