# Generated by Django 2.0 on 2020-07-07 05:14

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200706_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'MBBS'), (2, 'MBBCh'), (3, 'PhD'), (4, 'MPhil'), (5, 'FRCS'), (6, 'DTCD'), (7, 'FCCP'), (8, 'D-Card')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='designation',
            field=models.CharField(blank=True, choices=[('medical-officer', 'Medical Officer'), ('assistant-professor', 'Assistant Professor'), ('associate-professor', 'Associate Professor'), ('Professor ', 'Professor')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='religion',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('Hindu', 'Hindu'), ('buddhist', 'Buddhist'), ('cristian ', 'Cristian')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Doctor'),
        ),
    ]
