# Generated by Django 3.0 on 2020-12-11 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201210_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 14, 52, 58, 698427)),
        ),
        migrations.AlterField(
            model_name='foodblogview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 14, 52, 58, 706272)),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='medicine_image',
            field=models.ImageField(blank=True, upload_to='medcine_images'),
        ),
    ]
