# Generated by Django 3.0 on 2020-12-11 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201211_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 14, 55, 21, 686819)),
        ),
        migrations.AlterField(
            model_name='foodblogview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 14, 55, 21, 688826)),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='medicine_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.CategoryMedicine'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
