# Generated by Django 3.0 on 2020-12-11 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201211_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 14, 56, 17, 187433)),
        ),
        migrations.AlterField(
            model_name='foodblogview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 14, 56, 17, 187433)),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='medicine_image',
            field=models.ImageField(upload_to='medcine_images'),
        ),
    ]
