# Generated by Django 3.0 on 2020-12-11 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201211_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 15, 52, 44, 391421)),
        ),
        migrations.AlterField(
            model_name='foodblogview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 15, 52, 44, 392427)),
        ),
        migrations.AlterField(
            model_name='foodblogview',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
