# Generated by Django 2.0 on 2020-07-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
