# Generated by Django 3.0 on 2020-12-12 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201211_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 12, 10, 0, 29, 904951)),
        ),
        migrations.AlterField(
            model_name='foodblogview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 10, 0, 29, 904951)),
        ),
    ]
