# Generated by Django 3.0 on 2020-12-13 16:01

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201212_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='description',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 22, 1, 36, 60815)),
        ),
        migrations.AlterField(
            model_name='foodblogview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 22, 1, 36, 61854)),
        ),
    ]
