# Generated by Django 3.0 on 2020-12-14 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201213_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 14, 15, 35, 46, 78406)),
        ),
        migrations.AlterField(
            model_name='foodblogview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 15, 35, 46, 78406)),
        ),
    ]
