# Generated by Django 2.0 on 2020-07-08 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_staff'),
        ('home', '0010_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='technician_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Staff'),
        ),
    ]
