# Generated by Django 2.0 on 2020-07-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_lab_technician_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
