# Generated by Django 2.0 on 2020-07-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200708_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
