# Generated by Django 3.0 on 2020-12-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201220_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodblogview',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
