# Generated by Django 2.0 on 2020-07-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200709_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='compelete',
            field=models.BooleanField(default=False),
        ),
    ]
