# Generated by Django 2.0 on 2020-07-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_appointment_compelete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='compelete',
            new_name='complete',
        ),
    ]
