# Generated by Django 2.0 on 2020-07-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200709_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('price', models.IntegerField(blank=True, default=1)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
    ]
