# Generated by Django 2.0 on 2020-07-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
