# Generated by Django 2.0 on 2020-07-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_pharmacy_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.MedicineCompany'),
        ),
    ]
