# Generated by Django 2.0 on 2020-07-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200709_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
    ]
