# Generated by Django 2.0 on 2020-07-09 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_categorymedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='medicine_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.CategoryMedicine'),
        ),
    ]
