# Generated by Django 2.0 on 2020-07-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_pharmacy_medicine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='medicine_image',
            field=models.ImageField(blank=True, null=True, upload_to='medcine_images'),
        ),
    ]
