# Generated by Django 2.0 on 2020-07-10 15:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_pharmacy_medicine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='medcine_images')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
    ]
