# Generated by Django 2.0 on 2020-07-11 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_foodblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 11, 10, 25, 27, 382094)),
        ),
    ]
