# Generated by Django 2.1 on 2020-11-10 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20201110_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymedicine',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 10, 18, 38, 8, 921586)),
        ),
    ]
