# Generated by Django 2.1 on 2020-11-20 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20201120_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='per_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 20, 23, 1, 22, 651790)),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='price',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
