# Generated by Django 2.1 on 2020-11-22 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20201120_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='technician_name',
        ),
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 22, 11, 14, 55, 221105)),
        ),
    ]
