# Generated by Django 3.0 on 2020-11-29 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20201128_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 29, 11, 40, 27, 924752)),
        ),
    ]
