# Generated by Django 3.0 on 2020-12-04 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20201202_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 4, 20, 32, 20, 916399)),
        ),
        migrations.AlterField(
            model_name='foodblog',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images'),
        ),
    ]
