# Generated by Django 3.0 on 2020-12-06 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20201206_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 6, 23, 40, 56, 307312)),
        ),
    ]
