# Generated by Django 3.0 on 2020-12-09 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_auto_20201209_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 9, 23, 6, 54, 446169)),
        ),
    ]
